jenkins:
  image: 365351759635.dkr.ecr.us-east-1.amazonaws.com/jenkins

nginx:
  replicas: 1
  image: 365351759635.dkr.ecr.us-east-1.amazonaws.com/nginx

secrets:
  ecr-credentials:
    dockerconfigjson: |
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "<base64_encoded_credentials>"
          }
        }
      }

configmaps:
  jenkins.yaml: |
    systemMessage: "Welcome to my Jenkins Server!"
    numExecutors: 2
    securityRealm:
      local:
        allowsSignup: false
        users:
          - id: "jenkins-admin"
            password: "butler"
    authorizationStrategy:
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
