apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: {{ .Values.jenkins.image }}
        ports:
        - containerPort: 8080
        - containerPort: 50000
      imagePullSecrets:
      - name: ecr-credentials
      volumeMounts:
      - name: jenkins-config-volume
        mountPath: /var/jenkins_home/jenkins.yaml
        subPath: jenkins.yaml
  volumes:
  - name: jenkins-config-volume
    configMap:
      name: jenkins-config
